name: cxxsim tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  cxxsim-tests:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        platform: [wb, bb]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Chryse
      uses: chryse-hdl/setup-chryse-action@v2.2
      with:
        ref: v0.1.0
        install-oss-cad-suite: true
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Elaborate and run cxxsim
      run: sbt 'run cxxsim -Op ${{ matrix.platform }}'
